### ISSUE TITLE
Eval stuff is insecure

### ISSUE THREAD

**Issue by TheLBall** [TeamLuki/Maymayer#2]
Anyone can run eval. We are working to fix this.

**Comment by TheLBall** [comment]
just commited 3ffdad29963424af0c84c0b4b512914f0583852d and 05ecf171d35f5407beba3d398087c2a3f7808f29 @DeveloperTJ

**Comment by TheLBall** [comment]
- [x] Commit
- [ ] Test

**Comment by DeveloperTJ** [comment]
fixed some stuff
